### ISSUE TITLE
getplayerhandler.js weird bit of code

### ISSUE THREAD

**Issue by Karyum** [WebAhead7/NBA-API#4]
https://github.com/WebAhead7/NBA-API/blob/main/handlers/getplayerhandler.js#L6-L11

you don't really need this, you could just filter the player name by filtering the `allData` variable 

```javascript
//This function is responsible to filter the data according to the typed name/letters.
function getPlayerByName(name) {
  return allData.filter(player=>player.name.toLowerCase().startsWith(name.toLowerCase()));
}
```

and if you do want the names only you could something like this

```javascript
//This function is responsible to filter the data according to the typed name/letters.
function getPlayerByName(name) {
  return allData.map(player => player.name)
         .filter(player=>player.toLowerCase().startsWith(name.toLowerCase()));
}
```

**Comment by muhammadawwad9** [comment]
Fixed :100: , I really don't know why I declared this trivial extra array while I can map and filter! THX.
