### ISSUE TITLE
reuse the missingHandler

### ISSUE THREAD

**Issue by Karyum** [WebAhead7/NBA-API#6]
when something is not found you could just import and call the `missingHandler` instead of writing the same bit of code over and over again

### bad
```javascript
    response.writeHead(404,{"content-type":"text/html"});
    response.end(JSON.stringify("<h1>Something Went Wrong!</h1>"));
```

### good
```javascript
     missingHandler(request, response)
```

places where you need to add this
https://github.com/WebAhead7/NBA-API/blob/main/handlers/getdatahandler.js#L22-L25
https://github.com/WebAhead7/NBA-API/blob/main/handlers/homehandler.js#L7-L10
https://github.com/WebAhead7/NBA-API/blob/main/handlers/resourceshandler.js#L16-L18

**Comment by muhammadawwad9** [comment]
:+1: :100:
